from playsound import playsound
import time, Keys

print("            _____")
print("           | |   \ ")
print("           | |    \ ")
print("           | |     \___")
print("           | |         \ ")
print("           | |          \ ")
print("    0     _|_|___________|")
print("   /\/  /____|____________) ")
print(". /  \_|__________________| ")
print("|/__    | )(            )(") 
print("| |\|   :|)(  Fallen V  )(\n") 
print("----------------------------------------------------------------------------------------------------")
print("Welcome to our game!  In a couple of moments, you will have the chance to input a series of letters,")
print("and using that create a song of your choosing!  As of now, everything is in the 4th octave of the")
print("treble cleff.  Currently, you can only play up to eight notes at a time.  For example, to ")
print("play 'Merry Had A Little Lamb', you would type in 'E' as your first note, 'D' as your second, and")
print("so on, continuing with 'C-D-E-E-E-E').  The game IS CAPS SENSITIVE!  Have fun!")
print("----------------------------------------------------------------------------------------------------")
Menu = input("---------------------------------------\nType sandbox to play piano in a sandbox!\nType story to play piano in a story mode\n---------------------------------------\n")
    
if (Menu == "sandbox"):
    print("---------------------------------------------------------------------------------------")
    print("Welcome to the Sandbox")
    Tempo = input("\nWould you like a FAST or SLOW tempo, Type either 'Fast' or 'Slow' to choose\n---------------------------------------------------------------------------------------\n")
    print("---------------------------------------------------------------------------------------")
    print("Please Type the first Key you would like to press ")
    print("Commands: C=C4, D=D4, E=E4, F=F4, G=G4, A=A4, B=B4,")
    print("---------------------------------------------------------------------------------------")
    First_Key = input("First Key:\n")
    Sec_Key = input("Please input your second Key \n")
    Three_Key = input("Please input your third Key \n")
    Four_Key = input("Please input your fourth Key \n")
    Five_Key = input("Please input your fifth Key \n")
    Six_Key = input("Please input your sixth Key \n")
    Seven_Key = input("Please input your seventh Key \n")
    Eight_Key = input("Please input your eigth Key \n")
    if (Tempo == "Fast"):
        playsound(Keys.FirstKey(First_Key)[0]["First_Key"])
        playsound(Keys.SecKey(Sec_Key)[0]["Sec_Key"])
        playsound(Keys.ThreeKey(Three_Key)[0]["Three_Key"])
        playsound(Keys.FourKey(Four_Key)[0]["Four_Key"])
        playsound(Keys.FiveKey(Five_Key)[0]["Five_Key"])
        playsound(Keys.SixKey(Six_Key)[0]["Six_Key"])
        playsound(Keys.SevenKey(Seven_Key)[0]["Seven_Key"])
        playsound(Keys.EightKey(Eight_Key)[0]["Eight_Key"])

    if (Tempo == "Slow"):
        playsound(Keys.FirstKey(First_Key)[0]["First_Key"])
        time.sleep(1)
        playsound(Keys.SecKey(Sec_Key)[0]["Sec_Key"])
        time.sleep(1)
        playsound(Keys.ThreeKey(Three_Key)[0]["Three_Key"])
        time.sleep(1)
        playsound(Keys.FourKey(Four_Key)[0]["Four_Key"])
        time.sleep(1)
        playsound(Keys.FiveKey(Five_Key)[0]["Five_Key"])
        time.sleep(1)
        playsound(Keys.SixKey(Six_Key)[0]["Six_Key"])
        time.sleep(1)
        playsound(Keys.SevenKey(Seven_Key)[0]["Seven_Key"])
        time.sleep(1)
        playsound(Keys.EightKey(Eight_Key)[0]["Eight_Key"])

if (Menu == "story"):
    print("---------------------------------------------------------------------------------------")
    print("Welcome to the story mode, Level 1\n")
    print("---------------------------------------------------------------------------------------")
    print("Input the Following Keys: AACCEE")
    First_Key = input("Please input your first Key\n")
    Sec_Key = input("Please input your second Key \n")
    Three_Key = input("Please input your third Key \n")
    Four_Key = input("Please input your fourth Key \n")
    Five_Key = input("Please input your fifth Key \n")
    Six_Key = input("Please input your sixth Key \n")
    if(First_Key + Sec_Key + Three_Key + Four_Key + Five_Key + Six_Key == "AACCEE"):
        playsound('Sounds/A4.mp3')
        playsound('Sounds/A4.mp3')
        playsound('Sounds/C4.mp3')
        playsound('Sounds/C4.mp3')
        playsound('Sounds/E4.mp3')
        playsound('Sounds/E4.mp3')
        print("Great Job!")
    else:
        print("Failure, Please Restart")
    print("---------------------------------------------------------------------------------------")
    print("Welcome to the story mode, Level 2\n")
    print("---------------------------------------------------------------------------------------")
    print("Input the Following Keys: BCCEAA")
    First_Key = input("Please input your first Key\n")
    Sec_Key = input("Please input your second Key \n")
    Three_Key = input("Please input your third Key \n")
    Four_Key = input("Please input your fourth Key \n")
    Five_Key = input("Please input your fifth Key \n")
    Six_Key = input("Please input your sixth Key \n")
    if(First_Key + Sec_Key + Three_Key + Four_Key + Five_Key + Six_Key == "BCCEAA"):
        playsound('Sounds/B4.mp3')
        playsound('Sounds/C4.mp3')
        playsound('Sounds/C4.mp3')
        playsound('Sounds/E4.mp3')
        playsound('Sounds/A4.mp3')
        playsound('Sounds/A4.mp3')
        print("Great Job!")
    else:
        print("Failure, Please Restart")
    print("---------------------------------------------------------------------------------------")
    print("Welcome to the story mode, Level 3\n")
    print("---------------------------------------------------------------------------------------")
    print("Input the Following Keys: ABCEAE")
    First_Key = input("Please input your first Key\n")
    Sec_Key = input("Please input your second Key \n")
    Three_Key = input("Please input your third Key \n")
    Four_Key = input("Please input your fourth Key \n")
    Five_Key = input("Please input your fifth Key \n")
    Six_Key = input("Please input your sixth Key \n")
    if(First_Key + Sec_Key + Three_Key + Four_Key + Five_Key + Six_Key == "ABCEAE"):
        playsound('Sounds/A4.mp3')
        playsound('Sounds/B4.mp3')
        playsound('Sounds/C4.mp3')
        playsound('Sounds/E4.mp3')
        playsound('Sounds/A4.mp3')
        playsound('Sounds/E4.mp3')
        print("Great Job! You passed the campain so far! This will be added onto in the future. Thank you for playing!")
    else:
        print("Failure, Please Restart")
    print("---------------------------------------------------------------------------------------")
    print("Level 4, Type RICK")
    print("---------------------------------------------------------------------------------------")
    First_Key = input("Please input your first Key\n")
    Sec_Key = input("Please input your second Key \n")
    Three_Key = input("Please input your third Key \n")
    Four_Key = input("Please input your fourth Key \n")
    playsound('Sounds/RICK.mp3')
    
else:
    pass